In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
car=pd.read_csv('car_data.csv')

In [9]:
car.head()

name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   

   kms_driven fuel_type  
0  45,000 kms    Petrol  
1      40 kms    Diesel  
2  22,000 kms    Petrol  
3  28,000 kms    Petrol  
4  36,000 kms    Diesel

In [10]:
car.shape

(892, 6)

In [11]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
name          892 non-null object
company       892 non-null object
year          892 non-null object
Price         892 non-null object
kms_driven    840 non-null object
fuel_type     837 non-null object
dtypes: object(6)
memory usage: 41.9+ KB


##### Creating backup copy

In [12]:
backup=car.copy()

## Quality

- names are pretty inconsistent
- names have company names attached to it
- some names are spam like 'Maruti Ertiga showroom condition with' and 'Well mentained Tata Sumo'
- company: many of the names are not of any company like 'Used', 'URJENT', and so on.
- year has many non-year values
- year is in object. Change to integer
- Price has Ask for Price
- Price has commas in its prices and is in object
- kms_driven has object values with kms at last.
- It has nan values and two rows have 'Petrol' in them
- fuel_type has nan values

## Cleaning Data 

#### year has many non-year values

In [13]:
car=car[car['year'].str.isnumeric()]

#### year is in object. Change to integer

In [14]:
car['year']=car['year'].astype(int)

#### Price has Ask for Price

In [15]:
car=car[car['Price']!='Ask For Price']

#### Price has commas in its prices and is in object

In [16]:
car['Price']=car['Price'].str.replace(',','').astype(int)

####  kms_driven has object values with kms at last.

In [17]:
car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')

#### It has nan values and two rows have 'Petrol' in them

In [18]:
car=car[car['kms_driven'].str.isnumeric()]

In [19]:
car['kms_driven']=car['kms_driven'].astype(int)

#### fuel_type has nan values

In [20]:
car=car[~car['fuel_type'].isna()]

In [21]:
car.shape

(816, 6)

### name and company had spammed data...but with the previous cleaning, those rows got removed.

#### Company does not need any cleaning now. Changing car names. Keeping only the first three words

In [22]:
car['name']=car['name'].str.split().str.slice(start=0,stop=3).str.join(' ')

#### Resetting the index of the final cleaned data

In [23]:
car=car.reset_index(drop=True)

## Cleaned Data

In [59]:
# car

In [60]:
# car.to_csv('Cleaned_Car_data.csv')

In [61]:
# car.info()

In [62]:
# car.describe()

In [28]:
car=car[car['Price']<5000000]
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 815 entries, 0 to 815
Data columns (total 6 columns):
name          815 non-null object
company       815 non-null object
year          815 non-null int32
Price         815 non-null int32
kms_driven    815 non-null int32
fuel_type     815 non-null object
dtypes: int32(3), object(3)
memory usage: 35.0+ KB


In [63]:
# car.describe()

### Checking relationship of Company with Price

In [64]:
# car['company'].unique()

In [65]:
# import seaborn as sns

In [66]:
# plt.subplots(figsize=(15,7))
# ax=sns.boxplot(x='company',y='Price',data=car)
# ax.set_xticklabels(ax.get_xticklabels(),rotation=40,ha='right')
# plt.show()

### Checking relationship of Year with Price

In [67]:
# plt.subplots(figsize=(20,10))
# ax=sns.swarmplot(x='year',y='Price',data=car)
# ax.set_xticklabels(ax.get_xticklabels(),rotation=40,ha='right')
# plt.show()

### Checking relationship of kms_driven with Price

In [68]:
# sns.relplot(x='kms_driven',y='Price',data=car,height=7,aspect=1.5)

### Checking relationship of Fuel Type with Price

In [69]:
# plt.subplots(figsize=(14,7))
# sns.boxplot(x='fuel_type',y='Price',data=car)

### Relationship of Price with FuelType, Year and Company mixed

In [70]:
# ax=sns.relplot(x='company',y='Price',data=car,hue='fuel_type',size='year',height=7,aspect=2)
# ax.set_xticklabels(rotation=40,ha='right')

### Extracting Training Data

In [43]:
#Input Data
X=car[['name','company','year','kms_driven','fuel_type']]

# outputlabels
y=car['Price']

In [142]:
X

name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
812          Tata Indica V2      Tata  2009       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009      132000    Petrol
814            Tata Zest XM      Tata  2018       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

### Applying Train Test Split

In [127]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [128]:
from sklearn.linear_model import LinearRegression

In [115]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

#### Creating an OneHotEncoder object to contain all the possible categories

In [116]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

#### Creating a column transformer to transform categorical columns

In [117]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

#### Linear Regression Model

In [118]:
lr = LinearRegression()

#### Making a pipeline

In [119]:
pipe=make_pipeline(column_trans,lr)

#### Fitting the  model

In [129]:
pipe.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categorical_features=None,
                                                                categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'B...
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                drop=None,
                                                              

In [130]:
y_pred=pipe.predict(X_train)

In [144]:
# predictions = pd.DataFrame({'OriginalPrice':y_train, "PredictedPrice":y_pred})
# predictions

#### Checking R2 Score

In [132]:
r2_score(y_train,y_pred)

0.9495088638294161

In [133]:
from sklearn.metrics import mean_absolute_error as mae
mae(y_train,y_pred)

51592.64794201214

In [134]:
y_pred=pipe.predict(X_test)

In [135]:
r2_score(y_test,y_pred)

0.7852425416626871

#### Finding the model with a random state of TrainTestSplit where the model was found to give almost 0.92 as r2_score

In [ ]:
# import numpy as np
# from sklearn.model_selection import train_test_split
# X, y = np.arange(10).reshape((5, 2)), range(5)



In [136]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_train)
    scores.append(r2_score(y_train,y_pred))

In [138]:
np.argmax(scores)

82

In [110]:
scores

[0.8107876476922015,
 0.6020757204911074,
 0.6967422693355267,
 0.5091412715075501,
 0.8781865811842144,
 0.7555493285427632,
 0.4383035497698007,
 0.6341057022544676,
 0.5961569577815619,
 0.7320690267555192,
 0.8062571702322994,
 0.7638302518239102,
 0.49222604693770833,
 0.759784271508228,
 0.7802596497203038,
 0.6877806664133794,
 0.6468588564534293,
 0.713286382832689,
 0.7371386983057657,
 0.7772264946839792,
 0.7966538631668838,
 0.40314843120089716,
 0.7791459077788757,
 0.7761889243388952,
 0.5784383508725308,
 0.5045064756963189,
 0.7348601183895116,
 0.8323903561075285,
 0.8284980083679604,
 0.6118997874453952,
 0.6234117653356174,
 0.8541309991276522,
 0.7151400599630224,
 0.7899294266878376,
 0.8211262799997555,
 0.795966414830019,
 0.4918785304989568,
 0.7101800877883424,
 0.6930636113004505,
 0.8415165460916281,
 0.524196065161776,
 0.6872413724558286,
 0.5823578769387638,
 0.7033651452002854,
 0.8186008447416571,
 0.734602263273873,
 0.5905773847457441,
 0.5225429378797

In [139]:
scores[np.argmax(scores)]

0.9579677974741165

In [147]:
# name,company,fuel_type,year,km_driven = input('Enter Car details')
# pipe.predict()
record = pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5))

In [148]:
pipe.predict(record)

array([400707.28215338])

#### The best model is found at a certain random state 

In [66]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=665)
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.6406050430953001

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [68]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([416197.88186479])

In [140]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([400707.28215338])

In [71]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Toyota Corolla Altis','Toyota',2009,132000,'Petrol']).reshape(1,5)))

array([310277.67791338])

In [ ]:
Toyota Corolla Altis	Toyota	2009	132000	Petrol

In [143]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(["Tata Indica V2","Tata",2009,30000,'Diesel']).reshape(1,5)))

array([126539.83468379])

In [ ]:
pipe.steps[0][1].transformers[0][1].categories[0]