# Learning Numpy & Pandas for Data Analysis
    Structure => Numpy multidimesnsional array
    Super Fast processing
    Deals only Numerical values
    

# Creating a Numpy Array

# 1- Dimensional array

In [13]:
# Importing Numpy (Numerical Python) Module 
import numpy as np

In [14]:
# using Python List
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)

<class 'list'>


In [15]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
type(arr1d)

numpy.ndarray

In [17]:
arr1d[0]

1

In [18]:
arr1d[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr1d.max()

10

In [20]:
arr1d.min()

1

In [22]:
arr1d.sum()

55

In [28]:
arr1d.all()

True

In [31]:
lst = [1,2,3,4,5,6,7,8,9,10]
double= []
for a in lst:
    double.append(a*2)
double

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Vectorized Operation

In [32]:
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr1d/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [37]:
arr1d.size

10

In [38]:
arr1d.ndim

1

In [39]:
arr1d.shape

(10,)

In [43]:
# Array Creation using Numpy arange 
arr1d = np.arange(12)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 2D Array

In [51]:
# array using List
lst2d=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
lst2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [52]:
arr2d = np.array(lst2d)

In [53]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
arr2d.shape

(4, 3)

In [55]:
arr2d.ndim

2

In [56]:
arr2d+arr2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [57]:
arr2d*arr2d

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [60]:
arr3d = np.arange(36).reshape(6,6)
arr3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
arr3d.ndim

2

In [62]:
arr3d.shape

(6, 6)

In [79]:
arr4d=arr3d.reshape(9,4)
arr4d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [66]:
arr4d.ndim

2

In [67]:
arr4d.shape

(9, 4)

In [68]:
arr5d=arr3d.reshape(10,4)
arr5d

ValueError: cannot reshape array of size 36 into shape (10,4)

In [73]:
lst2d=[[1,2,3],[4,5,6],[7,8,9,29],[10,11,12]]
arr5d=np.array(lst2d)
arr5d

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 29]),
       list([10, 11, 12])], dtype=object)

In [75]:
arr1d[5]

5

In [76]:
arr1d[4:5]

array([4])

In [81]:
#index value 23 from array
arr4d[5][3]

23

In [82]:
arr4d[5,3]

23

In [86]:
arr5d=arr3d.reshape(4,9)
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [88]:
# two portion while we slcicing of an array of 2d arr arr[row,col] => [startrow:endrow,startcoloumn:endcoloumn]
arr5d[1:2,2:7]

array([[11, 12, 13, 14, 15]])

In [95]:
arr5d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [97]:
arr5d[0:,6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [98]:
# if we give all arguments of array in this array perform slicing [2:3,4:5] if any argument is missing then it return an index [:,2]
# return Index
arr5d[:,-1]

array([ 8, 17, 26, 35])

In [99]:
# Return slice
arr5d[0:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [101]:
arr5d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [102]:
arr5d[[0,2],[2,7]]

array([ 2, 25])

In [103]:
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [104]:
arr5d[:,::2]

array([[ 0,  2,  4,  6,  8],
       [ 9, 11, 13, 15, 17],
       [18, 20, 22, 24, 26],
       [27, 29, 31, 33, 35]])

In [105]:
arr5d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [106]:
arr5d[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [18, 20, 22, 24, 26]])

In [109]:
arr3d = np.arange(64).reshape(4,4,4) #(depth , row , coloumn)

In [108]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [169]:
arr3d[2,1,2]

38

In [118]:
arr3d[2,::]

array([[32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [119]:
arr3d[1:3,::]

array([[[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [120]:
arr3d[1:3,1:3:]

array([[[20, 21, 22, 23],
        [24, 25, 26, 27]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43]]])

In [122]:
arr3d[1:3,1:3,1:3]

array([[[21, 22],
        [25, 26]],

       [[37, 38],
        [41, 42]]])

In [129]:
arr3d[0:4,2,1:3]

array([[ 9, 10],
       [25, 26],
       [41, 42],
       [57, 58]])

In [131]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [133]:
np.zeros([4,5] ,dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [134]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [135]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [136]:
np.ones([5,5])*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [139]:
np.eye(10 ,dtype =int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [149]:
arr2d1=np.random.rand(4,3)
arr2d1

array([[0.96750398, 0.17843016, 0.03683178],
       [0.64059391, 0.66331835, 0.67113124],
       [0.29855189, 0.49709242, 0.21731572],
       [0.53789704, 0.68816263, 0.74851814]])

In [150]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [151]:
arr2d+arr2d1

array([[ 1.96750398,  2.17843016,  3.03683178],
       [ 4.64059391,  5.66331835,  6.67113124],
       [ 7.29855189,  8.49709242,  9.21731572],
       [10.53789704, 11.68816263, 12.74851814]])

In [153]:
arr2d - arr2d1

array([[ 0.03249602,  1.82156984,  2.96316822],
       [ 3.35940609,  4.33668165,  5.32886876],
       [ 6.70144811,  7.50290758,  8.78268428],
       [ 9.46210296, 10.31183737, 11.25148186]])

In [152]:
arr2d * arr2d1

array([[0.96750398, 0.35686033, 0.11049534],
       [2.56237562, 3.31659175, 4.02678743],
       [2.08986322, 3.97673933, 1.95584147],
       [5.37897039, 7.56978892, 8.9822177 ]])

In [154]:
a = np.arange(6).reshape(3,2)
b = np.arange(6).reshape(2,3)

In [155]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [156]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [157]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [158]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [159]:
# matrix Multiplication
b@a

array([[10, 13],
       [28, 40]])

In [160]:
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [161]:
a = np.arange(15).reshape(5,3)
b = np.arange(10).reshape(2,5)

In [162]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [163]:
b@a

array([[ 90, 100, 110],
       [240, 275, 310]])

In [164]:
a.dot(b)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [166]:
b.dot(a)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [178]:
np.full([4,5],10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [173]:
#Generate data with Equal Distribution 
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [175]:
np.linspace(1,100,50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [182]:
a.shape ,type(a)

((5, 3), numpy.ndarray)

In [179]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [183]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Boolean Selection Filters/Query

In [184]:
arr1d>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [185]:
(arr1d>5).sum()

6

In [194]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [195]:
c= [True,False,True,True,False,True,True,False,True,True,False,True]

In [196]:
c

[True, False, True, True, False, True, True, False, True, True, False, True]

In [197]:
arr1d[c]

array([ 0,  2,  3,  5,  6,  8,  9, 11])

In [198]:
arr1d[arr1d>5]

array([ 6,  7,  8,  9, 10, 11])

In [201]:
arr1d[arr1d==5]

array([5])

In [207]:
arr1d[arr1d % 2 != 0]

array([ 1,  3,  5,  7,  9, 11])

In [208]:
arr1d[arr1d % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [214]:
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [217]:
arr5d[ arr5d>10 ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [220]:
arr5d[(arr5d>10 ) & (arr5d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [227]:
arr5d[(arr5d>10 ) | (arr5d<30)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [231]:
arr5d.ravel()

In [243]:
arr5d.flatten()

array([ 0,  1,  2,  4,  4,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [234]:
d = arr5d.ravel()

In [235]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [238]:
d[3:6]=4

In [239]:
d

array([ 0,  1,  2,  4,  4,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [249]:
arr5d

array([[ 0,  1,  2,  4,  4,  4,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [244]:
e = arr5d.flatten()

In [245]:
e

array([ 0,  1,  2,  4,  4,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [246]:
e[0:6] = 10

In [247]:
e

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [250]:
arr5d

array([[ 0,  1,  2,  4,  4,  4,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [252]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [253]:
arr5d

array([[ 0,  1,  2,  4,  4,  4,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [257]:
arr5d1= arr5d[:]*5

In [258]:
arr5d1

array([[  0,   5,  10,  20,  20,  20,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [260]:
new5d = np.concatenate([arr5d,arr5d1],axis = 0)
new5d

array([[  0,   1,   2,   4,   4,   4,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [  0,   5,  10,  20,  20,  20,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [261]:
new5d = np.concatenate([arr5d,arr5d1],axis = 1)
new5d

array([[  0,   1,   2,   4,   4,   4,   6,   7,   8,   0,   5,  10,  20,
         20,  20,  30,  35,  40],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17,  45,  50,  55,  60,
         65,  70,  75,  80,  85],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  90,  95, 100, 105,
        110, 115, 120, 125, 130],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35, 135, 140, 145, 150,
        155, 160, 165, 170, 175]])

In [262]:
new5d1 =np.vstack([arr5d1,arr5d])

In [263]:
new5d1

array([[  0,   5,  10,  20,  20,  20,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175],
       [  0,   1,   2,   4,   4,   4,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35]])

In [264]:
new5d1 =np.hstack([arr5d1,arr5d])

In [266]:
new5d1

array([[  0,   5,  10,  20,  20,  20,  30,  35,  40,   0,   1,   2,   4,
          4,   4,   6,   7,   8],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85,   9,  10,  11,  12,
         13,  14,  15,  16,  17],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130,  18,  19,  20,  21,
         22,  23,  24,  25,  26],
       [135, 140, 145, 150, 155, 160, 165, 170, 175,  27,  28,  29,  30,
         31,  32,  33,  34,  35]])

In [268]:
new5d1 =np.dstack([arr5d1,arr5d])

In [269]:
new5d1

array([[[  0,   0],
        [  5,   1],
        [ 10,   2],
        [ 20,   4],
        [ 20,   4],
        [ 20,   4],
        [ 30,   6],
        [ 35,   7],
        [ 40,   8]],

       [[ 45,   9],
        [ 50,  10],
        [ 55,  11],
        [ 60,  12],
        [ 65,  13],
        [ 70,  14],
        [ 75,  15],
        [ 80,  16],
        [ 85,  17]],

       [[ 90,  18],
        [ 95,  19],
        [100,  20],
        [105,  21],
        [110,  22],
        [115,  23],
        [120,  24],
        [125,  25],
        [130,  26]],

       [[135,  27],
        [140,  28],
        [145,  29],
        [150,  30],
        [155,  31],
        [160,  32],
        [165,  33],
        [170,  34],
        [175,  35]]])

In [270]:
f = np.arange(9).reshape(3,3)
g= np.arange(10,19).reshape(3,3)

In [271]:
h= np.dstack((f,g))

In [273]:
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [274]:
g

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [275]:
h

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

In [276]:
arr5d

array([[ 0,  1,  2,  4,  4,  4,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [279]:
np.split(arr5d,2 ,axis=0)

[array([[ 0,  1,  2,  4,  4,  4,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [284]:
np.split(arr5d,3 ,axis=1)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [27, 28, 29]]), array([[ 4,  4,  4],
        [12, 13, 14],
        [21, 22, 23],
        [30, 31, 32]]), array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [33, 34, 35]])]

# Broadcasting

In [285]:
arr = np.arange(5)

In [286]:
arr

array([0, 1, 2, 3, 4])

In [287]:
arr.mean()

2.0

In [290]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)


In [291]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [292]:
b

array([0, 1, 2])

In [293]:
c = a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [307]:
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
b=np.broadcast_arrays(x, y)

In [308]:
b

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

# 2.Pandas

In [309]:
import pandas as pd

In [310]:
s1 = pd.Series(['Ahmed','Ahsan','Ali'])

In [311]:
s1

0    Ahmed
1    Ahsan
2      Ali
dtype: object

In [312]:
type(s1)

pandas.core.series.Series

In [313]:
s1[2]

'Ali'

In [314]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [315]:
s1[3] = "Farhan"

In [316]:
s1

0     Ahmed
1     Ahsan
2       Ali
3    Farhan
dtype: object

In [317]:
s1[2:4]

2       Ali
3    Farhan
dtype: object

In [322]:
# Fanncy Indexing
s1[[2,0]]

2      Ali
0    Ahmed
dtype: object

In [324]:
s1[s1 == 'Ali']

2    Ali
dtype: object

In [392]:
s2 =pd.Series([13,15,18,20,24],index=['apples','oranges','banana','grapes','avacado'])

In [393]:
s2

apples     13
oranges    15
banana     18
grapes     20
avacado    24
dtype: int64

In [394]:
s2['apples']

13

In [395]:
s2*2

apples     26
oranges    30
banana     36
grapes     40
avacado    48
dtype: int64

In [397]:
s2['apples':'grapes']

apples     13
oranges    15
banana     18
grapes     20
dtype: int64

In [398]:
s3 =pd.Series([13,15,18,20,24],index=[0,1,2,3,4])

In [399]:
s3[0:3]

0    13
1    15
2    18
dtype: int64

In [400]:
s3.loc[0:3]

0    13
1    15
2    18
3    20
dtype: int64

In [401]:
s2.iloc[0:3]

apples     13
oranges    15
banana     18
dtype: int64

In [403]:
s2.loc['apples':'grapes']

apples     13
oranges    15
banana     18
grapes     20
dtype: int64

In [404]:
s4 =pd.Series([13,15,18,20,24],index=['Apples','Oranges','Banana','Grapes','Avacado'])

In [405]:
s4

Apples     13
Oranges    15
Banana     18
Grapes     20
Avacado    24
dtype: int64

In [406]:
s2 + s4

Apples    NaN
Avacado   NaN
Banana    NaN
Grapes    NaN
Oranges   NaN
apples    NaN
avacado   NaN
banana    NaN
grapes    NaN
oranges   NaN
dtype: float64

<b>concept of Alignment<b>

In [409]:
s1 = pd.Series([1,2,3],dtype =int)

In [408]:
s1

0    1
1    2
2    4
dtype: int32

In [414]:
s2 = pd.Series([np.nan],dtype ='float')

In [415]:
s2

0   NaN
dtype: float64

In [416]:
s1.append(s2)

0    1.0
1    2.0
2    3.0
0    NaN
dtype: float64