In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Normalizer
import matplotlib.pyplot as plt

In [36]:
data = pd.read_csv('Dataset/Ecommerce Customers')

In [37]:
data.head()

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   

                                             Address            Avatar  \
0       835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1     4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3   1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4  14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [38]:
data.columns

Index(['Email', 'Address', 'Avatar', 'Avg. Session Length', 'Time on App',
       'Time on Website', 'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [39]:
data.Avatar.unique()

array(['Violet', 'DarkGreen', 'Bisque', 'SaddleBrown', 'MediumAquaMarine',
       'FloralWhite', 'DarkSlateBlue', 'Aqua', 'Salmon', 'Brown',
       'Tomato', 'RoyalBlue', 'DarkBlue', 'Peru', 'PowderBlue',
       'OliveDrab', 'Cyan', 'LightSeaGreen', 'PeachPuff', 'Black',
       'Olive', 'Silver', 'Wheat', 'Teal', 'Linen', 'MediumSlateBlue',
       'LemonChiffon', 'DarkOrchid', 'SeaGreen', 'SteelBlue',
       'DarkMagenta', 'DarkGoldenRod', 'DarkSeaGreen', 'Gainsboro',
       'HotPink', 'HoneyDew', 'WhiteSmoke', 'GhostWhite', 'Chocolate',
       'Snow', 'BurlyWood', 'Moccasin', 'BlueViolet', 'MediumBlue',
       'GreenYellow', 'SandyBrown', 'MediumVioletRed', 'DarkOliveGreen',
       'DarkSalmon', 'DeepPink', 'SkyBlue', 'Magenta', 'DarkTurquoise',
       'SpringGreen', 'OrangeRed', 'LimeGreen', 'LightGreen',
       'LightYellow', 'MintCream', 'DimGray', 'Indigo', 'LightSalmon',
       'DeepSkyBlue', 'Turquoise', 'LightSteelBlue', 'Cornsilk',
       'DarkKhaki', 'FireBrick', 'SlateGray',

In [42]:
data.drop(['Address', 'Email'], axis=1 , inplace =True)

In [43]:
data

Avatar  Avg. Session Length  Time on App  Time on Website  \
0              Violet            34.497268    12.655651        39.577668   
1           DarkGreen            31.926272    11.109461        37.268959   
2              Bisque            33.000915    11.330278        37.110597   
3         SaddleBrown            34.305557    13.717514        36.721283   
4    MediumAquaMarine            33.330673    12.795189        37.536653   
..                ...                  ...          ...              ...   
495               Tan            33.237660    13.566160        36.417985   
496     PaleVioletRed            34.702529    11.695736        37.190268   
497          Cornsilk            32.646777    11.499409        38.332576   
498              Teal            33.322501    12.391423        36.840086   
499       DarkMagenta            33.715981    12.418808        35.771016   

     Length of Membership  Yearly Amount Spent  
0                4.082621           587.951054  
1                2.664034           392.204933  
2                4.104543           487.547505  
3                3.120179           581.852344  
4                4.446308           599.406092  
..                    ...                  ...  
495              3.746573           573.847438  
496              3.576526           529.049004  
497              4.958264           551.620145  
498              2.336485           456.469510  
499              2.735160           497.778642  

[500 rows x 6 columns]

In [51]:
data ['Avatar'] = pd.get_dummies(data.Avatar)

In [52]:
data

Avatar  Avg. Session Length  Time on App  Time on Website  \
0         0            34.497268    12.655651        39.577668   
1         0            31.926272    11.109461        37.268959   
2         0            33.000915    11.330278        37.110597   
3         0            34.305557    13.717514        36.721283   
4         0            33.330673    12.795189        37.536653   
..      ...                  ...          ...              ...   
495       0            33.237660    13.566160        36.417985   
496       0            34.702529    11.695736        37.190268   
497       0            32.646777    11.499409        38.332576   
498       0            33.322501    12.391423        36.840086   
499       0            33.715981    12.418808        35.771016   

     Length of Membership  Yearly Amount Spent  
0                4.082621           587.951054  
1                2.664034           392.204933  
2                4.104543           487.547505  
3                3.120179           581.852344  
4                4.446308           599.406092  
..                    ...                  ...  
495              3.746573           573.847438  
496              3.576526           529.049004  
497              4.958264           551.620145  
498              2.336485           456.469510  
499              2.735160           497.778642  

[500 rows x 6 columns]

In [53]:
data = pd.read_csv('Dataset/Boston.csv')
data

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [55]:
data.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'price'],
      dtype='object')

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
crim       506 non-null float64
zn         506 non-null float64
indus      506 non-null float64
chas       506 non-null int64
nox        506 non-null float64
rm         506 non-null float64
age        506 non-null float64
dis        506 non-null float64
rad        506 non-null int64
tax        506 non-null int64
ptratio    506 non-null float64
black      506 non-null float64
lstat      506 non-null float64
price      506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [224]:
X =data.iloc[:,:-1]

In [225]:
X

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [226]:
X.shape

(506, 13)

In [227]:
y = data.price.values

In [228]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [229]:
y.shape

(506,)

In [230]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [231]:
X_train.shape

(379, 13)

In [232]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [233]:
predictions = regressor.predict(X_test)

In [234]:
pd.DataFrame({"original":y_test, 'pred':predictions})


original       pred
0        22.6  24.952333
1        50.0  23.616997
2        23.0  29.205886
3         8.3  11.960705
4        21.2  21.333620
..        ...        ...
122      19.4  17.538048
123      21.2  21.502223
124      20.3  23.632813
125      18.8  20.282598
126      33.4  35.179734

[127 rows x 2 columns]

In [14]:
from sklearn.metrics import r2_score
#r2_score(y_test,predictions)

In [15]:
from sklearn.metrics import mean_squared_error
#mean_squared_error(y_test,predictions)

In [237]:
X.max()

crim        88.9762
zn         100.0000
indus       27.7400
chas         1.0000
nox          0.8710
rm           8.7800
age        100.0000
dis         12.1265
rad         24.0000
tax        711.0000
ptratio     22.0000
black      396.9000
lstat       37.9700
dtype: float64

In [238]:
X/X.max()

crim    zn     indus  chas       nox        rm    age       dis  \
0    0.000071  0.18  0.083273   0.0  0.617681  0.748861  0.652  0.337278   
1    0.000307  0.00  0.254867   0.0  0.538462  0.731321  0.789  0.409607   
2    0.000307  0.00  0.254867   0.0  0.538462  0.818337  0.611  0.409607   
3    0.000364  0.00  0.078587   0.0  0.525832  0.797039  0.458  0.499913   
4    0.000776  0.00  0.078587   0.0  0.525832  0.814009  0.542  0.499913   
..        ...   ...       ...   ...       ...       ...    ...       ...   
501  0.000704  0.00  0.430065   0.0  0.657865  0.750911  0.691  0.204395   
502  0.000509  0.00  0.430065   0.0  0.657865  0.697039  0.767  0.188636   
503  0.000683  0.00  0.430065   0.0  0.657865  0.794533  0.910  0.178741   
504  0.001232  0.00  0.430065   0.0  0.657865  0.773804  0.893  0.196998   
505  0.000533  0.00  0.430065   0.0  0.657865  0.686788  0.808  0.206572   

          rad       tax   ptratio     black     lstat  
0    0.041667  0.416315  0.695455  1.000000  0.131156  
1    0.083333  0.340366  0.809091  1.000000  0.240716  
2    0.083333  0.340366  0.809091  0.989746  0.106136  
3    0.125000  0.312236  0.850000  0.994281  0.077430  
4    0.125000  0.312236  0.850000  1.000000  0.140374  
..        ...       ...       ...       ...       ...  
501  0.041667  0.383966  0.954545  0.987629  0.254675  
502  0.041667  0.383966  0.954545  1.000000  0.239136  
503  0.041667  0.383966  0.954545  1.000000  0.148538  
504  0.041667  0.383966  0.954545  0.991308  0.170661  
505  0.041667  0.383966  0.954545  1.000000  0.207532  

[506 rows x 13 columns]

In [239]:
X = Normalizer().fit_transform(X)
X

array([[1.26388341e-05, 3.59966795e-02, 4.61957387e-03, ...,
        3.05971776e-02, 7.93726783e-01, 9.95908132e-03],
       [5.78529889e-05, 0.00000000e+00, 1.49769546e-02, ...,
        3.77071843e-02, 8.40785474e-01, 1.93620036e-02],
       [5.85729947e-05, 0.00000000e+00, 1.51744622e-02, ...,
        3.82044450e-02, 8.43137761e-01, 8.64965806e-03],
       ...,
       [1.23765824e-04, 0.00000000e+00, 2.43009593e-02, ...,
        4.27762066e-02, 8.08470305e-01, 1.14884669e-02],
       [2.24644719e-04, 0.00000000e+00, 2.44548909e-02, ...,
        4.30471676e-02, 8.06519433e-01, 1.32831260e-02],
       [9.69214289e-05, 0.00000000e+00, 2.43887924e-02, ...,
        4.29308164e-02, 8.11392431e-01, 1.61092778e-02]])

In [240]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [241]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [242]:
predictions = regressor.predict(X_test)

In [243]:
pd.DataFrame({"original":y_test, 'pred':predictions})


original       pred
0        22.6  24.183209
1        50.0  20.856318
2        23.0  28.927447
3         8.3  12.318762
4        21.2  21.196297
..        ...        ...
122      19.4  16.453424
123      21.2  20.883865
124      20.3  22.639111
125      18.8  19.568823
126      33.4  36.446503

[127 rows x 2 columns]

In [244]:
r2_score(y_test,predictions)

0.6283003565294919

In [245]:
mean_squared_error(y_test,predictions)

30.36749491020761

In [246]:
#from sklearn.preprocessing import StandardScaler
#X = StandardScaler().fit_transform(X)
#X

In [247]:
#X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [248]:
#standardized_X = X.transform(X_train)
#standardized_X_test = X.transform(X_test)

In [249]:
#regressor.fit(standardized_X, y_train)

In [250]:
#predictions = regressor.predict(standardized_X_test)

In [251]:
#pd.DataFrame({"original":y_test, 'pred':predictions})


In [252]:
#r2_score(y_test,predictions)

In [253]:
#mean_squared_error(y_test,predictions)

In [254]:
from sklearn.linear_model import Lasso
model = Lasso(alpha=1)

In [255]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [256]:
model.fit(X_train, y_train)

Lasso(alpha=1, copy_X=True, fit_intercept=True, max_iter=1000, normalize=False,
      positive=False, precompute=False, random_state=None, selection='cyclic',
      tol=0.0001, warm_start=False)

In [257]:
predictions = model.predict(X_test)

In [258]:
pd.DataFrame({"original":y_test, 'pred':predictions})


original       pred
0        22.6  22.608707
1        50.0  22.608707
2        23.0  22.608707
3         8.3  22.608707
4        21.2  22.608707
..        ...        ...
122      19.4  22.608707
123      21.2  22.608707
124      20.3  22.608707
125      18.8  22.608707
126      33.4  22.608707

[127 rows x 2 columns]

In [259]:
r2_score(y_test,predictions)

-0.001119359203955339

In [223]:
mean_squared_error(y_test,predictions)

55.50347298051177

In [265]:
model = Lasso(alpha=0.1)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
pd.DataFrame({"original":y_test, 'pred':predictions})


original       pred
0        22.6  21.366924
1        50.0  17.852366
2        23.0  25.697336
3         8.3  18.402827
4        21.2  22.318009
..        ...        ...
122      19.4  27.136018
123      21.2  22.717832
124      20.3  24.922689
125      18.8  28.368329
126      33.4  27.814954

[127 rows x 2 columns]

In [266]:
r2_score(y_test,predictions)


0.125821340703117

In [267]:
mean_squared_error(y_test,predictions)

71.41953578149317

In [268]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
pd.DataFrame({"original":y_test, 'pred':predictions})


original       pred
0        22.6  22.025270
1        50.0  17.517260
2        23.0  24.755282
3         8.3  17.819101
4        21.2  22.132525
..        ...        ...
122      19.4  26.511664
123      21.2  22.377673
124      20.3  24.342355
125      18.8  26.680789
126      33.4  28.489008

[127 rows x 2 columns]

In [269]:
r2_score(y_test,predictions)


0.15711550967772436

In [270]:
mean_squared_error(y_test,predictions)

68.86283298731638

In [24]:
df = pd.read_csv('Dataset/Boston.csv')
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [25]:
X =df.iloc[:,:-1]
X

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [26]:
y= df.price
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [40]:
X = Normalizer().fit_transform(X)
X

array([[1.26388341e-05, 3.59966795e-02, 4.61957387e-03, ...,
        3.05971776e-02, 7.93726783e-01, 9.95908132e-03],
       [5.78529889e-05, 0.00000000e+00, 1.49769546e-02, ...,
        3.77071843e-02, 8.40785474e-01, 1.93620036e-02],
       [5.85729947e-05, 0.00000000e+00, 1.51744622e-02, ...,
        3.82044450e-02, 8.43137761e-01, 8.64965806e-03],
       ...,
       [1.23765824e-04, 0.00000000e+00, 2.43009593e-02, ...,
        4.27762066e-02, 8.08470305e-01, 1.14884669e-02],
       [2.24644719e-04, 0.00000000e+00, 2.44548909e-02, ...,
        4.30471676e-02, 8.06519433e-01, 1.32831260e-02],
       [9.69214289e-05, 0.00000000e+00, 2.43887924e-02, ...,
        4.29308164e-02, 8.11392431e-01, 1.61092778e-02]])

In [34]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [59]:
from sklearn import linear_model
model = linear_model.Lasso(alpha=0.0005)

In [60]:
model.fit(X_train, y_train)

Lasso(alpha=0.0005, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [64]:
predictions = model.predict(X_train)
predictions

array([13.80020426, 21.50767274, 33.40359436, 18.96873544, 12.87121794,
       15.62426776, 21.48747713, 14.42975485, 33.02279324, 24.53025577,
       15.24279738, 25.25260428,  9.44444915, 14.93050865, 20.73114185,
       34.22047643, 29.06387754, 24.26322743, 16.24848122, 29.58705248,
       30.29707721, 13.87133082, 10.24706519, 28.76297625, 26.88379655,
        5.99108573, 28.67596488, 18.11861799, 28.31336033, 20.21391988,
       16.44109411, 17.26366237, 12.46786623,  9.71550075, 20.20402705,
       35.57999466, 33.24049487, 26.37589857, 20.24143375, 23.28303473,
       26.61605452, 21.9471579 , 17.05108449, 31.91029694, 11.56636086,
       19.74672253, 28.30390765, 18.40198107, 15.78086302, 18.34770222,
       14.52787213, 22.40675246, 24.38462595, 17.36957547, 11.59076045,
       21.51781883, 23.3235808 , 16.40497101, 26.22261356, 24.21477809,
       28.68421573, 38.60479092, 16.6871448 , 12.62926578, 35.50485608,
       31.38732268, 20.68937134, 40.68811867, 28.2500243 , 27.67

In [66]:
pd.DataFrame({"original":y_train, 'pred':predictions})

original       pred
245      18.5  13.800204
59       19.6  21.507673
276      33.2  33.403594
395      13.1  18.968735
416       7.5  12.871218
..        ...        ...
323      18.5  19.353351
192      36.4  31.624874
117      19.2  22.381950
47       16.6  17.701178
172      23.1  21.283518

[379 rows x 2 columns]

In [62]:
r2_score(y_train,predictions)

0.7650903833425052

In [68]:
mean_squared_error(y_train,predictions)

20.039724906464333

In [17]:
y_train

245    18.5
59     19.6
276    33.2
395    13.1
416     7.5
       ... 
323    18.5
192    36.4
117    19.2
47     16.6
172    23.1
Name: price, Length: 379, dtype: float64

In [18]:
X_train

array([[3.70542740e-04, 4.26067019e-02, 1.13488761e-02, ...,
        3.69903639e-02, 7.53615723e-01, 3.57508962e-02],
       [2.10083113e-04, 5.08528062e-02, 1.04349958e-02, ...,
        4.00720113e-02, 8.07339152e-01, 1.87545149e-02],
       [2.22940079e-04, 8.51810406e-02, 1.36502618e-02, ...,
        3.74796579e-02, 8.28918001e-01, 1.28836324e-02],
       ...,
       [2.55316547e-04, 0.00000000e+00, 1.69275310e-02, ...,
        3.01009043e-02, 6.67140885e-01, 1.74179390e-02],
       [4.92577262e-04, 0.00000000e+00, 1.48458537e-02, ...,
        3.84574213e-02, 8.43785902e-01, 4.03910347e-02],
       [2.76325725e-04, 0.00000000e+00, 8.04311618e-03, ...,
        3.29668466e-02, 7.88225386e-01, 2.91736733e-02]])

In [63]:
model.coef_

array([ -95.37871271,   16.43412274,   -3.53595461,    0.        ,
         -0.        , 2199.80582209,   -4.71918417, -427.20571963,
         94.3536313 ,   -5.51252631, -401.94393864,    6.49380518,
       -262.39830908])